<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to NumPy:
</p><br>
<p><img src='numpy.jpeg'></p>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

<b>Additional Recommended Resources:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentation</a><br>
<i>Python for Data Analysis</i> by Wes McKinney<br>
<i>Python Data science Handbook</i> by Jake VanderPlas



<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Getting started with ndarray<br><br></p>

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy.  Let's get started by creating ndarrays using the numpy package.

In [1]:
import numpy as np  ##convention

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Rank 1 numpy arrays (or Vectors):
</p>

In [2]:
an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(an_array)

[  3  33 333]


In [3]:
l = [1,2,3,4,5]
print(type(l))
my_array = np.array(l)
print(my_array)

<class 'list'>
[1 2 3 4 5]


In [4]:
l[0] = 9
l

[9, 2, 3, 4, 5]

In [ ]:
print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

In [ ]:
# test the shape of the array we just created, it should have just one dimension (Rank 1)
print(an_array.shape)

In [ ]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0]) 

In [ ]:
an_array[0] =888            # ndarrays are mutable, here we change an element of the array

print(an_array)

In [ ]:
another_array = np.array((2, 22, 222))  # another way of creating an array
print(another_array)

In [ ]:
a = (2,3,4)
print(a)
print(type(a))
b = np.array(a)
print(b)
print(type(b))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Rank 2 numpy array (or Matrices):</p>

A rank 2 **ndarray** is one with two dimensions.  Notice the format below of [ [row] , [row] ].  2 dimensional arrays are great for representing matrices which are often useful in data science.

In [ ]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array
print()
print(type(another))  # The type of an ndarray is: "<class 'numpy.ndarray'>"
print()
print(another.shape)  # rows x columns  
print()
print(another[0, 0], another[0, 1], another[1, 0])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

There are many way to create numpy arrays:
</p>

Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [ ]:
# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)                              

In [ ]:
np.zeros((9,4))

In [ ]:
type(ex1[0,0])

In [ ]:
multi = np.zeros((3,3,3))  #3-dimensional array
print(multi)
print(multi.shape)
print(multi[0][2][1])

In [ ]:
multimulti = np.zeros((3,3,3,3))
print(multimulti)
print(multimulti.shape)

In [ ]:
# create a rank1 array of zeros
ex1 = np.zeros(4)
print(ex1)
print(ex1.shape)

<p style="font-family: Arial; font-size:1.5em;color:purple; font-style:bold"><br>

Converting between Ranks
</p>

In [ ]:
# convert rank1 array to rank2 array
ex1 = np.zeros(4)
print(ex1)
ex1 = ex1.reshape(2,2)
print(ex1)
print(ex1.shape)

In [ ]:
# convert rank1 array to rank2 array
print(ex1)
print(ex1.shape)
ex1 = ex1.reshape(4,)
print(ex1)
print(ex1.shape)

In [ ]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

In [ ]:
ex = np.full((4,4), 9)
print(ex)

In [ ]:
# create a 2x2 identity matrix with the diagonal 1s and the others 0
ex3 = np.eye(4,4)
print(ex3)  

In [ ]:
ex = np.eye(4,2)
print(ex)

In [ ]:
# create an array of ones
ex4 = np.ones(9).reshape(3,3).reshape(9,1).reshape(9,).reshape(3,3)
print(ex4)    

In [ ]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x4 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

In [ ]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((3,3))
print(ex5)    

In [ ]:
print(ex5[1,0])
print(ex5[1][0])

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Array Indexing
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Slice indexing:
</p>

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

In [5]:
# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [7]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


When you modify a slice, you actually modify the underlying array.

In [ ]:
print(an_array)   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print(an_array)    

In [ ]:
a_slice

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Use both integer indexing & slice indexing
</p>

We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [8]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [11]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[:, 3]    # Rank 1 view 

print(row_rank1, row_rank1.shape)  # notice only a single []

[14 24 34] (3,)


In [12]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [ ]:
#We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

Sometimes it's useful to use an array of indexes to access or change elements.

In [13]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [15]:
# Create an array of indices
col_indices = np.array([2, 1, 0, 1])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [2 1 0 1]

Rows indices picked :  [0 1 2 3]


In [16]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for i in zip(row_indices, col_indices):
    print(i)

(0, 2)
(1, 1)
(2, 0)
(3, 1)


In [ ]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

In [ ]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] *= 100000

print('\nChanged Array:')
print(an_array)

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
** *Boolean Indexing **

<br><br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

In [17]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [146]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 150)
print(filter)
filter.any()

[[False False]
 [False False]
 [False False]]


False

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [19]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

[21 22 31 32]


In [20]:
# For short, we could have just used the approach below without the need for the separate filter array.

an_array[(an_array % 2 == 0)]

array([12, 22, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter.  Let's add 100 to all the even values.

In [21]:
an_array[an_array % 2 == 0] += 5
print(an_array)

[[11 17]
 [21 27]
 [31 37]]


In [ ]:
surot = np.random.random(64).reshape(8,8) * 255
print(surot)

In [ ]:
print(surot[surot < 50])

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Datatypes and Array Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Datatypes:
</p>

In [ ]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

In [23]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [ ]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

In [22]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [24]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Arithmetic Array Operations:

</p>

In [25]:
x = np.array([[1,2],[3,4]], dtype=np.int)
y = np.array([[1.1,2.1],[3.1,4.1]], dtype=np.float64)

print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[1.1 2.1]
 [3.1 4.1]]


In [26]:
# add
print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"

[[2.1 4.1]
 [6.1 8.1]]

[[2.1 4.1]
 [6.1 8.1]]


In [ ]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

In [27]:
# multiply (elementwise)
print(x * y)
print()
print(np.multiply(x, y))

[[ 1.1  4.2]
 [ 9.3 16.4]]

[[ 1.1  4.2]
 [ 9.3 16.4]]


In [ ]:
# divide
print(x / y)
print()
print(np.divide(x, y))

In [ ]:
# square root
print(np.sqrt(x))

In [ ]:
# exponent (e ** x)
print(np.exp(x))

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Statistical Methods, Sorting, and <br> <br> Set Operations:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Basic Statistical Operations:
</p>

In [28]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[ -0.19230085   0.38916056  -4.94959048  -3.00943174   0.70645725]
 [ -9.83135152  -3.6515561   25.18587622  12.86460914 -14.23263084]]


In [29]:
# compute the mean for all elements
print(arr.mean())

0.32792416341758324


In [30]:
# compute the means by row
print(arr.mean(axis = 1))

[-1.41114105  2.06698938]


In [31]:
# compute the means by column
print(arr.mean(axis = 0))

[-5.01182618 -1.63119777 10.11814287  4.9275887  -6.7630868 ]


In [ ]:
# sum all the elements
print(arr.sum())

In [ ]:
# compute the medians
print(np.median(arr, axis = 1))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sorting:
</p>


In [ ]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

In [ ]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

In [ ]:
# inplace sorting
unsorted.sort() 

print(unsorted)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Finding Unique elements:
</p>

In [32]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Set Operations with np.array data type:
</p>

In [ ]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

In [ ]:
print( np.intersect1d(s1, s2) ) 

In [ ]:
print( np.union1d(s1, s2) )

In [ ]:
print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2

In [ ]:
print( np.in1d(s1, s2) )#which element of s1 is also in s2

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Broadcasting:
<br><br>
</p>

Introduction to broadcasting. <br>
For more details, please see: <br>
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [61]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [62]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [63]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [45]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

Example from the slides:

In [ ]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

In [ ]:
# create our 4x1 array
arrB = [0,1,0,2]
print(arrB)

In [ ]:
# add the two together using broadcasting
print(arrA + arrB)

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Speedtest: ndarrays vs lists
<br><br>
</p>

First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [ ]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [ ]:
# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

In [ ]:
# timer expects the operation as a parameter, 
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

In [ ]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

In [ ]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Read or Write to Disk:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Binary Format:</p>

In [69]:
x = np.array([ 23.23, 24.24, 12706, 0.0000127] )

In [65]:
np.save('an_array', x)

In [66]:
np.load('an_array.npy')

array([23.23, 24.24])

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Text Format:</p> 

In [70]:
np.savetxt('array.txt', X=x, delimiter=',')  #Save an array to a text file.

In [ ]:
!cat array.txt

In [71]:
np.loadtxt('array.txt', delimiter=',')

array([2.3230e+01, 2.4240e+01, 1.2706e+04, 1.2700e-05])

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Additional Common ndarray Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Dot Product on Matrices and Inner Product on Vectors:

</p>

In [72]:
# determine the dot product of two matrices
x2d = np.array([[1,2],[3,4]])
y2d = np.array([[5,6],[7,8]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [73]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


In [74]:
# dot product on an array and vector
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

[27 63]

[27 63]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sum:
</p>

In [75]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])
print(ex1)
print(np.sum(ex1))          # add all members

[[11 12]
 [21 22]]
66


In [ ]:
print(np.sum(ex1, axis=0))  # columnwise sum

In [ ]:
print(np.sum(ex1, axis=1))  # rowwise sum

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Element-wise Functions: </p>

For example, let's compare two arrays values to get the maximum of each.

In [76]:
# random array from the “standard normal” distribution
x = np.random.randn(8)
x

array([-1.48666209,  1.52672924,  0.6077003 , -2.42759213, -1.22946255,
       -0.34578463,  0.06583529, -0.30682423])

In [77]:
# another random array
y = np.random.randn(8)
y

array([ 0.26968874,  0.60767545, -0.42607603,  0.13813357,  0.72836686,
       -1.13957833, -0.02012039,  0.89648464])

In [78]:
# returns element wise maximum between two arrays

np.maximum(x, y)

array([ 0.26968874,  1.52672924,  0.6077003 ,  0.13813357,  0.72836686,
       -0.34578463,  0.06583529,  0.89648464])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Reshaping array:
</p>

In [ ]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

In [ ]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Transpose:

</p>

In [79]:
# transpose
ex1 = np.array([[11,12],[21,22]])
print(ex1)
ex2 = ex1.T
print(ex2)

[[11 12]
 [21 22]]
[[11 21]
 [12 22]]


# >>>>End of the First Part (to be continued)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Indexing using where():</p>

In [80]:
# Return elements, either from x or y, depending on condition
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [81]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [82]:
mat = np.random.rand(5,5)  #Random values in a given shape
mat

array([[0.48588686, 0.59425738, 0.92376691, 0.04481578, 0.01872602],
       [0.50623839, 0.46927531, 0.17541412, 0.66407803, 0.40246993],
       [0.55306357, 0.15943274, 0.19206148, 0.16410347, 0.44944524],
       [0.72893085, 0.10760719, 0.77596952, 0.48634639, 0.93500624],
       [0.45336653, 0.24597404, 0.73742157, 0.08765491, 0.93761847]])

In [83]:
np.where( mat > 0.5, 1000, -1)

array([[  -1, 1000, 1000,   -1,   -1],
       [1000,   -1,   -1, 1000,   -1],
       [1000,   -1,   -1,   -1,   -1],
       [1000,   -1, 1000,   -1, 1000],
       [  -1,   -1, 1000,   -1, 1000]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

"any" or "all" conditionals:</p>

In [84]:
arr_bools = np.array([ True, False, True, True, False ])

In [85]:
# Test whether any array element along a given axis evaluates to True.
arr_bools.any()

True

In [93]:
# Test whether all array elements along a given axis evaluate to True.
arr_bools.all()

False

In [88]:
a = np.random.rand(4,4)
a

array([[0.11008181, 0.01091155, 0.24756476, 0.76284662],
       [0.67186235, 0.02613648, 0.50042845, 0.65620893],
       [0.68675352, 0.72608591, 0.51129391, 0.10147314],
       [0.59637754, 0.25196034, 0.84130259, 0.1051256 ]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Random Number Generation:
</p>

In [94]:
# Draw random samples from a normal (Gaussian) distribution.
Y = np.random.normal(size = (1,5))[0]
print(Y)

[-0.92913946  1.30221639 -0.16918413 -0.98518879 -0.06281334]


In [126]:
# Return random integers from low (inclusive) to high (exclusive).
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[39 16  3 12]


In [100]:
a = np.random.randint(10, 100, 16).reshape(4,4)
a

array([[57, 29, 97, 29],
       [86, 72, 87, 54],
       [83, 56, 29, 39],
       [46, 56, 48, 85]])

In [136]:
# Randomly permute a sequence, or return a permuted range.
np.random.permutation(Z) #return a new ordering of elements in Z

array([39, 16, 12,  3])

In [137]:
np.random.uniform(size=4) #uniform distribution

array([0.69318095, 0.07486396, 0.5060783 , 0.43229789])

In [138]:
np.random.normal(size=4) #normal distribution

array([-0.67374432, -2.66858118, -1.05550187, -1.5394103 ])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Merging data sets:
</p>

In [139]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[ 9 29]
 [43 27]]

[[48 26]
 [11 37]]


In [140]:
# Stack arrays in sequence vertically (row wise).
np.vstack((K,M))

array([[ 9, 29],
       [43, 27],
       [48, 26],
       [11, 37]])

In [141]:
# Stack arrays in sequence horizontally (column wise).
np.hstack((K,M))

array([[ 9, 29, 48, 26],
       [43, 27, 11, 37]])

In [142]:
# Join a sequence of arrays along an existing axis.
np.concatenate([K, M], axis = 0)

array([[ 9, 29],
       [43, 27],
       [48, 26],
       [11, 37]])

In [143]:
np.concatenate([K, M.T], axis = 1)

array([[ 9, 29, 48, 11],
       [43, 27, 26, 37]])